
# Installer un package avec yum
- name: "Install a single package"
  yum:
    name: epel-release    # Epel-release est un repository Centos contenant plein de super packages
    state: installed

# Installer plusieurs packages avec yum, méthode 1
- name: "Install several packages, method 1"
  yum:
    name: [curl, wget]
    state: installed

# Installer plusieurs packages avec yum, méthode 2, peut être utile pour itérer d'autres modules
- name: "Install several packages, method 2"
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - curl
  - python-pip
