
---
- hosts: databases              # Les actions ci dessous ne seront appliquées qu'aux hôtes du groupe base de données

  vars_files:
    - common_vars.yml           # Ici on charge un fichier de variables

  vars:
    variable2: variable2        # Ici on défini des variables pour le playbook

  pre_tasks:                    # Ici on invoque des tâches simple sans faire appel à des role.
    - name: "Check that linux distribution is Centos"
      assert:
        that:
          - "'{{ ansible_distribution }}' == 'CentOS'"

  roles:
    - {name: install-yum-package,   variable3: value3,             tags: ['yum']} # Les tags permettent de n'éxécuter que certaines actions
    - {name: template-configuration,                               tags: ['configuration']}
    - {name: modify-configuration,                                 tags: ['configuration']}
    - {name: misc-modules,                                         tags: ['configuration']}
